name: Continuous Integration

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install innosetup --no-progress --yes
      - name: Configure
        run: cmake .
      - name: Build
        run: cmake --build . -t setup
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: setup
          path: setup/Debug/*.exe
