name: Continuous Integration

# Triggers the workflow on push or pull request events
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake .
      - name: Build
        run: cmake --build . -t setup
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: setup/Debug/*.exe
